# 1. Transfermarkt

In [7]:
import pandas as pd
from pathlib import Path
import json
import os

In [2]:
folder = Path("../data/transfermarkt_datasets")
summary = []

# On regarde le nombre de lignes, colonnes et NA par fichier csv

for file in folder.glob("*.csv"):
    df = pd.read_csv(file)

    summary.append({
        "fichier": file.name,
        "lignes": len(df),
        "colonnes": len(df.columns),
        "NA": df.isna().sum().sum()
    })

print(pd.DataFrame(summary))

C:\Users\LouisHarle\AppData\Local\Temp\ipykernel_11980\1118935329.py:7: DtypeWarning: Columns (0: number) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

                  fichier   lignes  colonnes       NA
0         appearances.csv  1862208        13        2
1               clubs.csv      796        17     1597
2          club_games.csv   173966        11   104264
3        competitions.csv       67        11       42
4           countries.csv      118         8        0
5               games.csv    86983        23    82284
6         game_events.csv  1242945        11  1782275
7        game_lineups.csv  3049833        10        3
8      national_teams.csv      118        17      127
9             players.csv    47702        26   188546
10  player_valuations.csv   616377         6    71820
11          transfers.csv   157186        10   115681

In [3]:
# Les 5 premières lignes des fichiers

for file in folder.glob("*.csv"):
    df = pd.read_csv(file)

    print(f"\n{file}")
    print(df.head())

..\data\transfermarkt_datasets\appearances.csv
    appearance_id  game_id  player_id  player_club_id  player_current_club_id  \
0   2231978_38004  2231978      38004             853                     235
1   2233748_79232  2233748      79232            8841                    2698
2   2234413_42792  2234413      42792            6251                     465
3   2234418_73333  2234418      73333            1274                      76
4  2234421_122011  2234421     122011             195                    3008

         date       player_name competition_id  yellow_cards  red_cards  \
0  2012-07-03  Aurélien Joachim            CLQ             0          0
1  2012-07-05    Ruslan Abyshov            ELQ             0          0
2  2012-07-05       Sander Puri            ELQ             0          0
3  2012-07-05   Vegar Hedenstad            ELQ             0          0
4  2012-07-05  Markus Henriksen            ELQ             0          0

   goals  assists  minutes_played
0      2        0              90
1      0        0              90
2      0        0              45
3      0        0              90
4      0        1              90

..\data\transfermarkt_datasets\clubs.csv
   club_id            club_code                   name  \
0       10    arminia-bielefeld      Arminia Bielefeld
1    10004             paris-fc    Paris Football Club
2    10010  esporte-clube-bahia    Esporte Clube Bahia
3     1003       leicester-city         Leicester City
4     1005             us-lecce  Unione Sportiva Lecce

  domestic_competition_id  total_market_value  squad_size  average_age  \
0                      L1                 NaN          27         25.3
1                     FR1                 NaN          31         28.5
2                    BRA1                 NaN          32         26.2
3                     GB1                 NaN          29         25.9
4                     IT1                 NaN          27         25.1

   foreigners_number  foreigners_percentage  national_team_players  \
0                 15                   55.6                      4
1                 17                   54.8                      8
2                  6                   18.8                      3
3                 17                   58.6                      9
4                 23                   85.2                     10

         stadium_name  stadium_seats net_transfer_record    coach_name  \
0         SchücoArena          26515             +€5.90m           NaN
1    Stade Jean Bouin          19904            €-72.30m           NaN
2    Arena Fonte Nova          47364             +€8.14m           NaN
3  King Power Stadium          32259            +€57.30m  Steve Cooper
4  Ettore Giardiniero          31559             +€8.62m           NaN

   last_season                                           filename  \
0         2021  ../data/raw/transfermarkt-scraper/2021/clubs.j...
1         2025  ../data/raw/transfermarkt-scraper/2025/clubs.j...
2         2025  ../data/raw/transfermarkt-scraper/2025/clubs.j...
3         2024  ../data/raw/transfermarkt-scraper/2024/clubs.j...
4         2025  ../data/raw/transfermarkt-scraper/2025/clubs.j...

                                                 url
0  https://www.transfermarkt.co.uk/arminia-bielef...
1  https://www.transfermarkt.co.uk/paris-fc/start...
2  https://www.transfermarkt.co.uk/esporte-clube-...
3  https://www.transfermarkt.co.uk/leicester-city...
4  https://www.transfermarkt.co.uk/us-lecce/start...

..\data\transfermarkt_datasets\club_games.csv
   game_id  club_id  own_goals  own_position own_manager_name  opponent_id  \
0  1026846     3449          2           NaN    Óscar Tabárez         3589
1  1026846     3589          1           NaN     Jung-moo Huh         3449
2  1026847     3437          3           NaN   Diego Maradona         6303
3  1026847     6303          1           NaN   Javier Aguirre         3437
4  1027001     3441          2           NaN  Milovan Rajevac         3505

   opponent_goals  opponent_position opponent_manager_name hosting  is_win
0               1                NaN          Jung-moo Huh    Home       1
1               2                NaN         Óscar Tabárez    Away       0
2               1                NaN        Javier Aguirre    Home       1
3               3                NaN        Diego Maradona    Away       0
4               1                NaN           Bob Bradley    Away       1

..\data\transfermarkt_datasets\competitions.csv
  competition_id       competition_code                   name  \
0             A1             bundesliga             bundesliga
1           AFAC          afc-asian-cup          afc-asian-cup
2           AFCN  africa-cup-of-nations  africa-cup-of-nations
3           ARG1        torneo-apertura        torneo-apertura
4           AUS1           a-league-men           a-league-men

                sub_type                       type  country_id country_name  \
0             first_tier            domestic_league         127      Austria
1          afc_asian_cup  national_team_competition          -1          NaN
2  africa_cup_of_nations  national_team_competition          -1          NaN
3             first_tier            domestic_league           9    Argentina
4             first_tier            domestic_league          12    Australia

  domestic_league_code confederation  total_clubs  \
0                   A1        europa         12.0
1                  NaN         asien          NaN
2                  NaN        afrika          NaN
3                 ARG1       amerika         30.0
4                 AUS1         asien         12.0

                                                 url
0  https://www.transfermarkt.co.uk/bundesliga/sta...
1  https://www.transfermarkt.co.uk/afc-asian-cup/...
2  https://www.transfermarkt.co.uk/africa-cup-of-...
3  https://www.transfermarkt.co.uk/torneo-apertur...
4  https://www.transfermarkt.co.uk/a-league-men/s...

..\data\transfermarkt_datasets\countries.csv
   country_id     country_name country_code confederation  total_clubs  \
0          10          Armenia         ARM1        europa           10
1         100  North Macedonia         MAZ1        europa           12
2         103         Malaysia         MYS1         asien           13
3         106            Malta         MT1N        europa           12
4         107          Morocco         MAR1        afrika           16

   total_players  average_age  \
0            265         24.8
1            283         25.4
2            399         28.3
3            299         26.9
4            499         27.2

                                                 url
0  https://www.transfermarkt.co.uk/wettbewerbe/na...
1  https://www.transfermarkt.co.uk/wettbewerbe/na...
2  https://www.transfermarkt.co.uk/wettbewerbe/na...
3  https://www.transfermarkt.co.uk/wettbewerbe/na...
4  https://www.transfermarkt.co.uk/wettbewerbe/na...

..\data\transfermarkt_datasets\games.csv
   game_id competition_id  season        round        date  home_club_id  \
0  1026846           FIWC    2009  Round of 16  2010-06-26          3449
1  1026847           FIWC    2009  Round of 16  2010-06-27          3437
2  1027001           FIWC    2009  Round of 16  2010-06-26          3505
3  1027002           FIWC    2009  Round of 16  2010-06-27          3262
4  1027048           FIWC    2009  Round of 16  2010-06-28          3379

   away_club_id  home_club_goals  away_club_goals  home_club_position  ...  \
0          3589                2                1                 NaN  ...
1          6303                3                1                 NaN  ...
2          3441                1                2                 NaN  ...
3          3299                4                1                 NaN  ...
4          3503                2                1                 NaN  ...

                      stadium attendance           referee  \
0  Nelson Mandela Bay Stadium    30597.0    Wolfgang Stark
1                 FNB-Stadium    84377.0   Roberto Rosetti
2      Royal Bafokeng Stadium    34976.0     Viktor Kassai
3          Free State Stadium    40510.0   Jorge Larrionda
4       Moses Mabhida Stadion    61962.0  Undiano Mallenco

                                                 url  home_club_formation  \
0  https://www.transfermarkt.co.uk/spielbericht/i...                  NaN
1  https://www.transfermarkt.co.uk/spielbericht/i...                  NaN
2  https://www.transfermarkt.co.uk/spielbericht/i...                  NaN
3  https://www.transfermarkt.co.uk/spielbericht/i...                  NaN
4  https://www.transfermarkt.co.uk/spielbericht/i...                  NaN

  away_club_formation home_club_name away_club_name aggregate  \
0                 NaN        Uruguay    South Korea       2:1
1                 NaN      Argentina         Mexico       3:1
2                 NaN  United States          Ghana       1:2
3                 NaN        Germany        England       4:1
4                 NaN    Netherlands       Slovakia       2:1

            competition_type
0  national_team_competition
1  national_team_competition
2  national_team_competition
3  national_team_competition
4  national_team_competition

[5 rows x 23 columns]

..\data\transfermarkt_datasets\game_events.csv
                      game_event_id        date  game_id  minute  \
0  60d28dc455d299f5abdb65d7204fef40  2010-06-26  1026846      69
1  71280d139049475e02eb7627897da117  2010-06-26  1026846      38
2  dbb0d095a58423d8377d6b5b6b9f258f  2010-06-26  1026846       8
3  6948606e52c10f6a2032ebe64355fe14  2010-06-26  1026846      80
4  eb2ca121e9069fac2789c9e0be7cdbd3  2010-06-26  1026846      84

            type  club_id    club_name  player_id  \
0          Cards     3589  South Korea       1772
1          Cards     3589  South Korea      27402
2          Goals     3449      Uruguay      44352
3          Goals     3449      Uruguay      44352
4  Substitutions     3449      Uruguay      44352

                                         description  player_in_id  \
0                             1. Yellow card  , Foul           NaN
1                             1. Yellow card  , Foul           NaN
2  , Right-footed shot, 2. Tournament Goal Assist...           NaN
3  , Right-footed shot, 3. Tournament Goal Assist...           NaN
4                                         , Tactical       76213.0

   player_assist_id
0               NaN
1               NaN
2            3408.0
3           72653.0
4               NaN

C:\Users\LouisHarle\AppData\Local\Temp\ipykernel_11980\735796966.py:4: DtypeWarning: Columns (0: number) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

..\data\transfermarkt_datasets\game_lineups.csv
                    game_lineups_id        date  game_id  player_id  club_id  \
0  b2dbe01c3656b06c8e23e9de714e26bb  2013-07-27  2317258       1443      610
1  b50a3ec6d52fd1490aab42042ac4f738  2013-07-27  2317258       5017      610
2  7d890e6d0ff8af84b065839966a0ec81  2013-07-27  2317258       9602     1090
3  8c355268678b9bbc7084221b1f0fde36  2013-07-27  2317258      12282      610
4  76193074d549e5fdce4cdcbba0d66247  2013-07-27  2317258      25427     1090

         player_name             type            position number  team_captain
0  Christian Poulsen      substitutes  Defensive Midfield      5             0
1   Niklas Moisander  starting_lineup         Centre-Back      4             0
2    Maarten Martens      substitutes         Left Winger     11             0
3        Daley Blind  starting_lineup           Left-Back     17             0
4        Roy Beerens  starting_lineup        Right Winger     23             0

..\data\transfermarkt_datasets\national_teams.csv
   national_team_id        name   team_code  country_id country_name  \
0             10521  San Marino  san-marino         144   San Marino
1             10533     Andorra     andorra           5      Andorra
2             11953  Montenegro  montenegro         216   Montenegro
3             13342   Guatemala   guatemala          58    Guatemala
4             13497      Uganda      uganda         176       Uganda

  country_code confederation  \
0         SMR1          UEFA
1         AND2          UEFA
2         MNE1          UEFA
3         GU1A      CONCACAF
4         UGL1           CAF

                                      team_image_url  squad_size  average_age  \
0  https://tmssl.akamaized.net//images/flagge/hea...          24         24.6
1  https://tmssl.akamaized.net//images/flagge/hea...          28         28.4
2  https://tmssl.akamaized.net//images/flagge/hea...          24         26.4
3  https://tmssl.akamaized.net//images/flagge/hea...          21         25.1
4  https://tmssl.akamaized.net//images/flagge/hea...          28         27.9

   foreigners_number  foreigners_percentage  total_market_value  coach_name  \
0                 19                   79.2            935000.0         NaN
1                 16                   57.1           3520000.0         NaN
2                 23                   95.8          58130001.0         NaN
3                  6                   28.6           5380000.0         NaN
4                 23                   82.1           8630000.0         NaN

   fifa_ranking  last_season  \
0           210         2025
1           172         2025
2            82         2025
3            94         2025
4            88         2025

                                                 url
0  https://www.transfermarkt.co.uk/san-marino/sta...
1  https://www.transfermarkt.co.uk/andorra/starts...
2  https://www.transfermarkt.co.uk/montenegro/sta...
3  https://www.transfermarkt.co.uk/guatemala/star...
4  https://www.transfermarkt.co.uk/uganda/startse...

..\data\transfermarkt_datasets\players.csv
   player_id first_name     last_name                name  last_season  \
0         10   Miroslav         Klose      Miroslav Klose         2015
1         26      Roman  Weidenfeller  Roman Weidenfeller         2017
2         65    Dimitar      Berbatov    Dimitar Berbatov         2015
3         77        NaN         Lúcio               Lúcio         2012
4         80        Tom        Starke          Tom Starke         2017

   current_club_id         player_code    country_of_birth city_of_birth  \
0              398      miroslav-klose              Poland         Opole
1               16  roman-weidenfeller             Germany          Diez
2             1091    dimitar-berbatov            Bulgaria   Blagoevgrad
3              506               lucio              Brazil      Brasília
4               27          tom-starke  East Germany (GDR)       Freital

  country_of_citizenship  ...            agent_name  \
0                Germany  ...  ASBW Sport Marketing
1                Germany  ...      Neubauer 13 GmbH
2               Bulgaria  ...       CSKA-AS-23 Ltd.
3                 Brazil  ...                   NaN
4                Germany  ...                   IFM

                                           image_url international_caps  \
0  https://img.a.transfermarkt.technology/portrai...                NaN
1  https://img.a.transfermarkt.technology/portrai...                NaN
2  https://img.a.transfermarkt.technology/portrai...                NaN
3  https://img.a.transfermarkt.technology/portrai...                NaN
4  https://img.a.transfermarkt.technology/portrai...                NaN

  international_goals  current_national_team_id  \
0                 NaN                       NaN
1                 NaN                       NaN
2                 NaN                       NaN
3                 NaN                       NaN
4                 NaN                       NaN

                                                 url  \
0  https://www.transfermarkt.co.uk/miroslav-klose...
1  https://www.transfermarkt.co.uk/roman-weidenfe...
2  https://www.transfermarkt.co.uk/dimitar-berbat...
3  https://www.transfermarkt.co.uk/lucio/profil/s...
4  https://www.transfermarkt.co.uk/tom-starke/pro...

  current_club_domestic_competition_id  \
0                                  IT1
1                                   L1
2                                  GR1
3                                  IT1
4                                   L1

                                   current_club_name  market_value_in_eur  \
0                      Società Sportiva Lazio S.p.A.            1000000.0
1                                  Borussia Dortmund             750000.0
2  Panthessalonikios Athlitikos Omilos Konstantin...            1000000.0
3                             Juventus Football Club             200000.0
4                                  FC Bayern München             100000.0

   highest_market_value_in_eur
0                   30000000.0
1                    8000000.0
2                   34500000.0
3                   24500000.0
4                    3000000.0

[5 rows x 26 columns]

..\data\transfermarkt_datasets\player_valuations.csv
   player_id        date  market_value_in_eur current_club_name  \
0     405973  2000-01-20               150000           Unknown
1     342216  2001-07-20               100000           Unknown
2       3132  2003-12-09               400000       Dynamo Kyiv
3       6893  2003-12-15               900000       Galatasaray
4         10  2004-10-04              7000000  SV Werder Bremen

   current_club_id player_club_domestic_competition_id
0           3057.0                                 BE1
1           1241.0                                 SC1
2            126.0                                 TR1
3            984.0                                 GB1
4            398.0                                 IT1

..\data\transfermarkt_datasets\transfers.csv
   player_id transfer_date transfer_season  from_club_id  to_club_id  \
0     467994    2030-06-30           25/26          5621         749
1     784335    2027-07-18           27/28          6505        6502
2     402135    2027-07-04           27/28          6505         515
3     716435    2027-07-04           27/28          6505       30925
4     803933    2027-06-30           26/27          4467          14

    from_club_name     to_club_name  transfer_fee  market_value_in_eur  \
0         Reggiana        FC Empoli           0.0             700000.0
1  Gimcheon Sangmu  Jeonbuk Hyundai           0.0             500000.0
2  Gimcheon Sangmu     Without Club           NaN             350000.0
3  Gimcheon Sangmu       Gwangju FC           0.0             325000.0
4     TSV Hartberg   Austria Vienna           0.0             300000.0

         player_name
0  Luca Belardinelli
1      Jun-soo Byeon
2         Jun-su Ahn
3      Kang-hyun Lee
4      Luca Pazourek

In [5]:
# On prend le dataframe des joueurs
df = pd.read_csv("../data/transfermarkt_datasets/players.csv")

# On prend la colonne de la valeur marchande
df = df.dropna(subset=["market_value_in_eur"])

# On trie par valeur
df_sorted = df.sort_values("market_value_in_eur")

# On prend des profils aléatoires et les meilleurs
players_sample = pd.concat([
    df_sorted.sample(6),    # aléatoire
    df_sorted.tail(6)       # stars
])

print(players_sample[["name", "market_value_in_eur"]])

                      name  market_value_in_eur
31006          Lazar Micic             500000.0
23414    Vladislav Sarveli             700000.0
1909               William              25000.0
33848         Ibon Ispizua             100000.0
20241         Denis Adamov            2500000.0
24952  Frederik Roepstorff              50000.0
30618      Jude Bellingham          140000000.0
22408      Vinicius Junior          150000000.0
34346                Pedri          150000000.0
20835        Kylian Mbappé          200000000.0
24550       Erling Haaland          200000000.0
40538         Lamine Yamal          200000000.0

In [7]:
appearances = pd.read_csv("../data/transfermarkt_datasets/appearances.csv")

appearances

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,76,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1862203,4818788_607223,4818788,607223,281,281,2026-03-22,Rayan Cherki,CGB,0,0,0,0,90
1862204,4818788_655488,4818788,655488,11,11,2026-03-22,Gabriel Martinelli,CGB,0,0,0,0,8
1862205,4818788_659813,4818788,659813,11,11,2026-03-22,Piero Hincapié,CGB,1,0,0,0,65
1862206,4818788_743413,4818788,743413,281,281,2026-03-22,Nico O'Reilly,CGB,0,0,2,0,90
1862207,4818788_763079,4818788,763079,281,281,2026-03-22,Abdukodir Khusanov,CGB,1,0,0,0,90

In [8]:
appearances = pd.read_csv("../data/transfermarkt_datasets/appearances.csv")

# On prend les dates du csv
appearances["date"] = pd.to_datetime(appearances["date"])

# On prend uniquement l'année
appearances["year"] = appearances["date"].dt.year

# On compte le nombre d'années différentes
nb_annees = appearances["year"].nunique()

print("Nombre d'années d'historique :", nb_annees)

# On regarde l'année la plus récente
annee_plus_recente = appearances["year"].max()
print("Année la plus récente :", annee_plus_recente)

Nombre d'années d'historique : 15
Année la plus récente : 2026

In [9]:
# On prend toutes les années présentes du csv
annees_presentes = sorted(appearances["year"].unique())

# On crée une liste avec toutes les années de l'année minimale à
# l'année maximale
annees_completes = list(range(appearances["year"].min(),
                               appearances["year"].max() + 1))

# On compare la liste avec les années du csv à la liste avec toutes
# les années
annees_manquantes = sorted(set(annees_completes) - set(annees_presentes))

print("Années manquantes :", annees_manquantes)
# pas d'année manquante

Années manquantes : []

In [11]:
appearances["date"] = pd.to_datetime(appearances["date"])
appearances["year"] = appearances["date"].dt.year

comp = pd.read_csv("../data/transfermarkt_datasets/competitions.csv")

df_merge = comp.merge(
    comp[["competition_id", "country_name", "domestic_league_code"]],
    on="competition_id",
    how="left"
)

# garder uniquement les ligues présentes dans les données
ligues_presentes = df_merge["competition_id"].unique()

mapping = comp[comp["competition_id"].isin(ligues_presentes)][
    ["country_name", "domestic_league_code"]
].drop_duplicates()

print("Saisons disponibles :", sorted(map(int, appearances["year"].unique())))
print("Nombre total de joueurs :", appearances["player_id"].nunique())
print(mapping.sort_values("country_name"))

Saisons disponibles : [2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]
Nombre total de joueurs : 28665
      country_name domestic_league_code
3        Argentina                 ARG1
4        Australia                 AUS1
0          Austria                   A1
5          Belgium                  BE1
7           Brazil                 BRA1
14        Colombia                 COL1
36         Croatia                  KR1
61  Czech Republic                  TS1
18         Denmark                  DK1
10         England                  GB1
27          France                  FR1
16         Germany                   L1
31          Greece                  GR1
11           Italy                  IT1
34           Japan                 JAP1
49    Korea, South                 RSK1
38          Mexico                 MEX1
40     Netherlands                  NL1
43          Norway                  NO1
44          Poland                  PL1
45        Portugal                  PO1
48         Romania                  RO1
50          Russia                  RU1
53    Saudi Arabia                  SA1
54        Scotland                  SC1
57          Serbia                 SER1
9            Spain                  ES1
56          Sweden                  SE1
8      Switzerland                   C1
60         Türkiye                  TR1
63         Ukraine                 UKR1
39   United States                 MLS1
1              NaN                  NaN

# 2. FBref

In [3]:
folder = Path("../data/fbref_datasets")
summary = []

# On regarde le nombre de lignes, colonnes et NA apr fichier csv

for file in folder.glob("*.csv"):
    df = pd.read_csv(file)

    summary.append({
        "fichier": file.name,
        "lignes": len(df),
        "colonnes": len(df.columns),
        "NA": df.isna().sum().sum()
    })

print(pd.DataFrame(summary))

                            fichier  lignes  colonnes     NA
0        players_data-2025_2026.csv    2731       102  63994
1  players_data_light-2025_2026.csv    2731        53  37582

In [4]:
# Les 5 premières lignes des fichiers

for file in folder.glob("*.csv"):
    df = pd.read_csv(file)

    print(f"\n{file}")
    print(df.head())

..\data\fbref_datasets\players_data-2025_2026.csv
   Rk               Player   Nation    Pos              Squad  \
0   1     Brenden Aaronson   us USA  MF,FW       Leeds United
1   2          Zach Abbott  eng ENG     DF  Nottingham Forest
2   3  Jones El-Abdellaoui   ma MAR  MF,FW         Celta Vigo
3   4        Himad Abdelli   dz ALG  FW,MF          Marseille
4   5        Himad Abdelli   dz ALG     MF             Angers

                 Comp   Age    Born  MP  Starts  ...  CrdY_stats_misc  \
0  eng Premier League  25.0  2000.0  30      24  ...                1
1  eng Premier League  19.0  2006.0   2       1  ...                0
2          es La Liga  20.0  2006.0  20       4  ...                0
3          fr Ligue 1  26.0  1999.0   5       0  ...                1
4          fr Ligue 1  26.0  1999.0  13      11  ...                1

   CrdR_stats_misc  2CrdY  Fls  Fld  Off  Crs  Int  TklW  OG
0                0      0   17   43    5   35   13    22   0
1                0      0    2    1    0    3    2     2   0
2                0      0    5    3    2   26    3     3   0
3                0      0    3    0    0    1    1     1   0
4                0      0   16   12    1    9   13    17   0

[5 rows x 102 columns]

..\data\fbref_datasets\players_data_light-2025_2026.csv
   Rk               Player   Nation    Pos              Squad  \
0   1     Brenden Aaronson   us USA  MF,FW       Leeds United
1   2          Zach Abbott  eng ENG     DF  Nottingham Forest
2   3  Jones El-Abdellaoui   ma MAR  MF,FW         Celta Vigo
3   4        Himad Abdelli   dz ALG  FW,MF          Marseille
4   5        Himad Abdelli   dz ALG     MF             Angers

                 Comp   Age    Born  MP  Starts  ...  Save%   W   D   L  CS  \
0  eng Premier League  25.0  2000.0  30      24  ...    NaN NaN NaN NaN NaN
1  eng Premier League  19.0  2006.0   2       1  ...    NaN NaN NaN NaN NaN
2          es La Liga  20.0  2006.0  20       4  ...    NaN NaN NaN NaN NaN
3          fr Ligue 1  26.0  1999.0   5       0  ...    NaN NaN NaN NaN NaN
4          fr Ligue 1  26.0  1999.0  13      11  ...    NaN NaN NaN NaN NaN

   CS%  PKatt_stats_keeper  PKA  PKsv  PKm
0  NaN                 NaN  NaN   NaN  NaN
1  NaN                 NaN  NaN   NaN  NaN
2  NaN                 NaN  NaN   NaN  NaN
3  NaN                 NaN  NaN   NaN  NaN
4  NaN                 NaN  NaN   NaN  NaN

[5 rows x 53 columns]

In [5]:
players_data = pd.read_csv("../data/fbref_datasets/players_data-2025_2026.csv")

comp = players_data["Comp"]
players = players_data["Player"]

print(comp.unique())

print(comp.value_counts())

print("Nombre de joueurs analysés : ", len(players.value_counts()))

<StringArray>
['eng Premier League', 'es La Liga', 'fr Ligue 1', 'it Serie A',
 'de Bundesliga']
Length: 5, dtype: str
Comp
it Serie A            582
es La Liga            581
fr Ligue 1            540
eng Premier League    535
de Bundesliga         493
Name: count, dtype: int64
Nombre de joueurs analysés :  2579

# 3. Statsbomb

In [8]:
lineups_path = "../data/statsbomb_datasets/data/lineups"

players_list = []

for file in os.listdir(lineups_path):
    if file.endswith(".json"):
        with open(os.path.join(lineups_path, file), encoding="utf-8") as f:
            data = json.load(f)

            for team in data:
                team_name = team["team_name"]

                for player in team["lineup"]:
                    players_list.append({
                        "player_id": player.get("player_id"),
                        "player_name": player.get("player_name"),
                        "team": team_name,
                        "position": player.get("position", {}).get("name"),
                        "jersey_number": player.get("jersey_number")
                    })

# On crée le dataframe des joueurs
df_players = pd.DataFrame(players_list)

# On supprime les doublons
df_players = df_players.drop_duplicates(subset=["player_id"])

df_players.head()

,player_id,player_name,team,position,jersey_number
0,3109,Malcom Filipe Silva de Oliveira,Barcelona,None,14
1,3501,Philippe Coutinho Correia,Barcelona,None,7
2,5203,Sergio Busquets i Burgos,Barcelona,None,5
3,5211,Jordi Alba Ramos,Barcelona,None,18
4,5213,Gerard Piqué Bernabéu,Barcelona,None,3